### ISSUE TITLE
AsposeCellsCloud::ApiError: Bad Request

### ISSUE THREAD

**Issue by rodrigosol** [aspose-cells/Aspose.Cells-for-Cloud#14]
Hi There,

I am trying to use the README example but I am getting bad request error.

How can I enable debugging logs?

Any tips?

**Comment by farooqsheikhpk** [comment]
Hi @rodrigosol 

Can you please mention in which SDK API you are getting this Error? Each SDK has its own README.md file in its root folder. You can also check this out. 

Looking forward to hear from you to proceed further. 

Regards,
Farooq Sheikh

**Comment by rodrigosol** [comment]
Ruby SDK.

I have followed its readme.md.

Thanks

On Wednesday, April 27, 2016, Farooq Sheikh <notifications@github.com>
wrote:

> Hi @rodrigosol <https://github.com/rodrigosol>
>
> Can you please mention in which SDK API you are getting this Error? Each
> SDK has its own README.md file in its root folder. You can also check this
> out.
>
> Looking forward to hear from you to proceed further.
>
> Regards,
> Farooq Sheikh
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/aspose-cells/Aspose.Cells-for-Cloud/issues/14#issuecomment-215023219>
>


-- 
Rodrigo Sol

rodrigo@rarolabs.com.br
http://www.rarolabs.com.br

**Comment by sohail-aspose** [comment]
@rodrigosol,
Please make sure that you have given the **right path to the file** in following line of code.
`response = @cells_api.put_convert_work_book(File.open("data/" << file_name,"r") { |io| io.read }, {format: convert_to_format}) 
`   
I am sure that before calling this API, you have gotten the App key and App SID from https://cloud.aspose.com and inserted into following line of code.
`AsposeApp.app_key_and_sid("APP_KEY", "APP_SID")`

You can also run our [Unit Tests](https://github.com/aspose-cells/Aspose.Cells-for-Cloud/blob/master/SDKs/Aspose.Cells_Cloud_SDK_For_Ruby/test/cells_tests.rb) where everything is in place -- samples files are given in the [data](https://github.com/aspose-cells/Aspose.Cells-for-Cloud/tree/master/SDKs/Aspose.Cells_Cloud_SDK_For_Ruby/test/data) folder.
